[package]
name = "backend"
version = "0.1.0"
authors = ["Olle Sandberg <olle@b3rg.se>"]

[dependencies]
rocket = "*"
rocket_codegen = "*"
websocket = "*"
futures = "*"
tokio-core = "*"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"

